spring.application.name=patient-service


# UNCOMMENT TO USE IN MEMORY DATABASE OUTSIDE OF DOCKER
# Enable the H2 web console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console/**
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=sa
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

#spring.datasource.url=${DB_URL}
#spring.datasource.driver-class-name=${DB_DRIVER}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}
#spring.jpa.properties.hibernate.dialect =${JPA_DIALECT}
#spring.jpa.properties.hibernate.show_sql = ${JPA_SHOW_SQL_FLAG}
#spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
#spring.sql.init.mode=${SQL_INIT_MODE}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
#spring.kafka.bootstrap-servers=kafka:9092

#spring.kafka.producer.bootstrap-servers=localhost:9094
#spring.kafka.consumer.group-id=myGroup
server.port=4000
#logging.level.root=info

logging.level.org.apache.kafka.clients.producer.ProducerConfig=DEBUG
logging.level.org.apache.kafka.clients.consumer.ConsumerConfig=DEBUG
